=== Reposoft/rweb/www/navigation/navigation.dtd
<!ELEMENT navigation (#PCDATA | unit)*>
<!ELEMENT unit (#PCDATA | unit)*>
<!ATTLIST unit href CDATA #IMPLIED>
<!ATTLIST unit name CDATA #IMPLIED>
<!ATTLIST unit type CDATA #IMPLIED>

=== Reposoft/rweb/www/navigation/navigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="navigation.xsl"?>
<!DOCTYPE navigation SYSTEM "navigation.dtd">
<navigation>
    <!-- type attribute is a string from the DTD, used voluntarily by themes -->
    <unit name="Sven Svensson" type="user" href="/testuser">
        <unit name="repos" type="link" href="http://www.repos.se/"/>
    </unit>
	<unit name="projects" type="menu">
		<unit name="coordinator 2.5" type="project" href="/coordinator"/>
		<unit name="Infomonter" type="project" href="/infomonter">
		    <unit name="underprojekt" type="project" href="/infomonter/underprojekt">
		        <unit name="under underprojekt" type="project" href="/under underprojekt"/>
		    </unit>
		    <unit name="Nu du" type="project" href="/acompany/nowyou"/>
		</unit>
	</unit>
	<unit name="networks" type="menu">
	    <unit name="Optime" type="network" href="/optime"/>
	</unit>
	<unit name="finished projects" type="menu"/>
	<unit name="com-onweb" type="company"/>
</navigation>
